# Generated by Django 3.2.4 on 2021-06-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(to='item.Like'),
        ),
    ]
