# Generated by Django 3.2.4 on 2021-06-05 17:57

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itemmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.upload_directory_path),
        ),
    ]
