# Generated by Django 3.2.4 on 2021-06-07 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0007_alter_itemmodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='Item',
        ),
    ]
