# Generated by Django 3.2.4 on 2021-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_rename_itemmodel_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='item.Tag'),
        ),
    ]
