# Generated by Django 3.2.4 on 2021-06-09 00:00

from django.db import migrations
import imagekit.models.fields
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20210608_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='public/noimage.svg', null=True, upload_to=item.models.upload_directory_path),
        ),
    ]
