# Generated by Django 3.2.4 on 2021-06-09 00:24

from django.db import migrations
import imagekit.models.fields
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=item.models.upload_directory_path),
        ),
    ]
