# Generated by Django 3.2.4 on 2021-06-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210608_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='plofile',
            new_name='profile',
        ),
    ]
