# Generated by Django 3.2.4 on 2021-06-07 21:53

from django.db import migrations
import imagekit.models.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_plofile_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='public/avatar.svg', null=True, upload_to=user.models.CustomUser.user_directory_path),
        ),
    ]
